export default [
  { time: 12.62, text: "I'm sittin' here in the boring room" },
  { time: 17.11, text: "It's just another rainy Sunday afternoon" },
  { time: 19.85, text: "I'm wasting my time" },
  { time: 21.49, text: "I got nothin' to do" },
  { time: 23.49, text: "I'm hangin' around" },
  { time: 25.39, text: "I'm waitin' for you" },
  { time: 26.88, text: "But nothing ever happens and I wonder" },
  { time: 33.66, text: "I'm drivin' around in my car" },
  { time: 37.12, text: "I'm drivin' too fast" },
  { time: 38.52, text: "I'm drivin' too far" },
  { time: 40.25, text: "I'd like to change my point of view" },
  { time: 43.77, text: "I feel so lonely" },
  { time: 45.43, text: "I'm waitin' for you" },
  { time: 46.94, text: "But nothing ever happens and I wonder" },
  { time: 53.45, text: "I wonder how" },
  { time: 55.18, text: "I wonder why" },
  { time: 57.20, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 60.18, text: "And all that I can see is just a yellow lemon tree" },
  { time: 66.94, text: "I'm turnin' my head up and down" },
  { time: 70.68, text: "I'm turnin', turnin', turnin', turnin', turnin' around" },
  { time: 73.69, text: "And all that I can see is just another lemon tree" },
  { time: 79.19, text: "Sing!" },
  { time: 80.84, text: "Dap-dadada-dadpm-didap-da" },
  { time: 86.00, text: "Dadada-dadpm-didap-da" },
  { time: 89.51, text: "Dap-didili-da" },
  { time: 93.78, text: "I'm sittin' here" },
  { time: 95.76, text: "I miss the power" },
  { time: 97.53, text: "I'd like to go out takin' a shower" },
  { time: 100.51, text: "But there's a heavy cloud inside my head" },
  { time: 104.02, text: "I feel so tired" },
  { time: 105.77, text: "Put myself into bed" },
  { time: 107.25, text: "Well, nothing ever happens and I wonder" },
  { time: 113.67, text: "Isolation is not good for me" },
  { time: 121.40, text: "Isolation, I don't want to sit on the lemon tree" },
  { time: 127.90, text: "I'm steppin' around in the desert of joy" },
  { time: 131.18, text: "Baby, anyhow I'll get another toy" },
  { time: 134.42, text: "And everything will happen and you wonder" },
  { time: 141.11, text: "I wonder how" },
  { time: 142.83, text: "I wonder why" },
  { time: 144.31, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 147.57, text: "And all that I can see is just another lemon tree" },
  { time: 154.32, text: "I'm turnin' my head up and down" },
  { time: 157.82, text: "I'm turnin', turnin', turnin', turnin', turnin' around" },
  { time: 161.09, text: "And all that I can see is just a yellow lemon tree" },
  { time: 165.99, text: "And I wonder, wonder" },
  { time: 167.98, text: "I wonder how" },
  { time: 169.49, text: "I wonder why" },
  { time: 171.24, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 174.23, text: "And all that I can see" },
  { time: 178.13, text: "And all that I can see" },
  { time: 181.39, text: "And all that I can see" },
  { time: 184.04, text: "Is just a yellow lemon tree" },
];